<?php
    $form->prepare();
    $this->formlabel()->setTranslatorTextDomain('alsazfcontent');
    $this->formradio()->setTranslatorTextDomain('alsazfcontent');
    $this->formsubmit()->setTranslatorTextDomain('alsazfcontent');
?>
<div class="page-header">
    <h1><?php echo $this->translate('Create Content', 'alsazfcontent'); ?></h1>
</div>
<?php echo $this->form()->openTag($form); ?>
    <?php foreach ($form as $element): ?>
        <div class="form-group<?php if ($element->getMessages()) echo ' has-error'; ?>">
            <?php if ($element instanceof \Zend\Form\Element\Submit): ?>
                <?php echo $this->formelement($element->setAttribute('class', 'btn btn-primary')
                                                      ->setAttribute('value', $element->getLabel())); ?>
                <a href="<?php echo $this->url('zfcadmin/alsazfcontent'); ?>" class="btn btn-danger"><?php echo $this->translate('Cancel', 'alsazfcontent'); ?></a>
            <?php else: ?>
                <?php if ($element instanceof \Zend\Form\Element\Textarea) $element->setAttribute('rows', 10); ?>
                <?php echo $this->formlabel($element->setLabelAttributes(['class' => 'control-label'])); ?>
                <?php if ($element instanceof \Zend\Form\Element\Radio): ?>
                    <div class="radio">
                        <?php echo $this->formradio()->setSeparator('</div><div class="radio">')->render($element); ?>
                    </div>
                <?php else: ?>
                    <?php echo $this->formelement($element->setAttribute('class', 'form-control')); ?>
                <?php endif; ?>
                <?php echo $this->formelementerrors($element); ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
